sudo: required
language: node_js
node_js:
- '0.12'
before_install:
- curl https://install.meteor.com/ | sh
install:
- meteor npm install
services: mongodb
script:
- npm run linter
- npm run test
cache:
  bundler: true
  directories:
  - node_modules